version: "3"
services:
    server:
        image: multisweeper/server
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./docker-compose.yml:/usr/local/docker-compose.yml"
        deploy:
            replicas: 3
            update_config:
                parallelism: 3
                delay: 10s
            restart_policy:
               condition: none 
