version: "3"
services:
    server:
        image: multisweeper/server
        ports:
            - "8080:8080"
        deploy:
            replicas: 3
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
               condition: none 
