version: "3"
services:
    server:
        image: multisweeper/server
        #ports:
        #    - "8080:8080"
        networks:
            - broadcast-net
        volumes:
            - "./board.txt:/usr/local/board.txt"
        deploy:
            replicas: 3
            update_config:
                parallelism: 2
                delay: 1s
            restart_policy:
               condition: on-failure 
    lb:
        image: multisweeper/lb
        ports:
            - "8080:8080"
        networks:
            - broadcast-net
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 1s
            restart_policy:
               condition: on-failure 
               delay: 10s

networks:
    broadcast-net:
